resolver: nightly-2018-04-27

# Local packages, usually specified by relative directory name
packages:
    - '.'
    - location: ../motor
      #   git: https://github.com/owickstrom/motor.git
      #   commit: bf8f532b2a0d820c454f290d6eb0d538933caa8c
      subdirs:
        - motor
      extra-dep: true


# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
  - gi-gobject-2.0.16
  - gi-glib-2.0.16
  - gi-gst-1.0.15
  - gi-gdk-3.0.15
  - gi-gdkpixbuf-2.0.15
  - gi-gio-2.0.16
  - gi-gtk-3.0.21
  - gi-pango-1.0.16
  - gi-vte-2.91.17
  - indexed-0.1.3
  - indexed-extras-0.2
  - tasty-discover-4.2.0
  - row-types-0.2.2.0

allow-newer: true
