resolver: lts-12.4

packages:
- .

extra-deps:
 - ffmpeg-light-0.12.2.2
 - indexed-0.1.3
 - git: git@github.com:owickstrom/gi-gtk-declarative.git
   commit: bad182f0cf2617450e7d9fb9a3dbff18a20b3433
 - git: git@github.com:reinerp/indexed-extras.git
   commit: 8b38e7503c030644154e844cd932003d9438cfa2
 - massiv-0.1.6.1
 - motor-0.3.0
 - row-types-0.2.3.0
