resolver: lts-12.4

packages:
- .

extra-deps:
 - gi-gstbase-1.0.16
 - gi-gst-1.0.16
 - ffmpeg-light-0.12.2.2
 - indexed-0.1.3
 - massiv-0.1.6.1
 - motor-0.3.0
 - row-types-0.2.3.0
 - process-1.6.4.0
 - git: https://github.com/owickstrom/gi-gtk-declarative.git
   commit: 74bc5bdf5134ad7187fd96cc94ded52b7b4ca3b9
   subdirs:
     - gi-gtk-declarative
 - git: https://github.com/reinerp/indexed-extras.git
   commit: 8b38e7503c030644154e844cd932003d9438cfa2
 - git: https://github.com/robrix/fused-effects.git
   commit: 7421ffa4e2d05b961fb0347ddab5ebdef9e32f25
